### ISSUE TITLE
Add possibility to delete a Activity

### ISSUE THREAD

**Issue by atrandafir** [DracoBlue/activitystreams-php#1]
I could not find a method to delete a Activity, so I had to add a workaround.

It would be good to add the possibility to delete Activity by ID or by other fields inside the activity table, such as stream_id, actor_id, object_id, verb, and so on.

I needed this feature because I wanted to delete a activity without deleting the object from the database because it could be used by other activities.

So, in my Yii Framework component wrapper for the Activity Stream client, I've added the following method:

`public function deleteActivityByValues($values=array()) {
    if (count($values)==0)
      return false;
    $criteria=new CDbCriteria(array(
        'limit'=>1,
    ));
    $values['application_id']=$this->application_id;
    foreach ($values as $k => $v) {
      $criteria->addCondition("`$k`=:$k");
      $criteria->params[$k]=$v;
    }
    return ActivityStreamActivity::model()->deleteAll($criteria);
  }
`

And now I can call the following to delete a Activity from a certain Stream related to a certain Object:
`
Yii::app()->as->deleteActivityByValues(array(
              'stream_id'=>$stream->getId(),
              'object_id'=>$object->getId(),
          ));
`

**Comment by DracoBlue** [comment]
Hi,

as of 1.1.0 it is possible to delete an activity by using $application->deleteActivity($activity);

It is also possible to set a custom id for the activity. This _may_ (but I am not sure) help you. Let's say, you create a photo within your app and create an activity for this:

```
$photo = $this->createSuperCoolPhoto();
$activity_id = ''photo_created-' . $photo->getId();
$activity = $user_stream->createActivity(array('id' => $activity_id, 'title' => 'I made a photo', 'verb' => 'post'));
```

Then when the photo get's removed and you want to get also rid of the activity: you can fetch the activity by using this:

```
$activity = $application->getActivityById($activity_id);
// and remove it
$application->deleteActivity($activity);
```

Would this help? Currently there is no getActivityById-method, though.

**Comment by atrandafir** [comment]
Yes I think this would be useful in some cases when you want to delete only one activity.

**Comment by DracoBlue** [comment]
`getActivityById` added!
