### ISSUE TITLE
Prevent showing again the same activities when loading the next page of activities

### ISSUE THREAD

**Issue by atrandafir** [DracoBlue/activitystreams-php#4]
Right now I've got a profile page where I show one users latest activities. At the bottom of the page there's a "load more" button that loads with ajax the next "page" of activities.

So the ajax call basically runs the getFeed method with a different offset.

The problem I find is that if in the meanwhile more activities were created, or were deleted, then when we load the new ones, we will either repeat some activities that were already shown, or we skip some activities that haven't been shown yet.

**Comment by DracoBlue** [comment]
With 1.2.0 you may use the getFeed method with a third parameter. This parameter is the last activity of the previous feed.

It works like this:

```
$guest->getFeed(0, 20, $first_activity)
```

will return all activities BEFORE $first_activity.
